version: "3.9"
services:
  ibax:
    env_file:
      - .env
    hostname: ibax
    restart: always
    image: ibax/go-ibax:latest
    container_name: ibax
    volumes:
      - ./data/ibax:/mnt/ibax/data
      - ./data/ibax/test.log:/mnt/ibax/data/test.log
      - ./data/cert:/mnt/cert
    depends_on:
      - postgresql
      - redis
      - centrifugo
    links:
      - postgresql:postgresql
      - redis:redis
      - centrifugo:centrifugo
    ports:
      - "7078:7078"
      - "7079:7079"
  postgresql:
    hostname: postgresql
    restart: always
    image: postgres:13
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      TZ: UTC
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - postgresql-data:/var/lib/postgresql/data
  redis:
    hostname: redis
    restart: always
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v3
    volumes:
      - "./data/centrifugo:/centrifugo"
      - "./data/cert:/mnt/cert"
    command: centrifugo -c config.json --admin --tls=${CENTRIFUGO_TLS}
    ports:
      - "8000:8000"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
#volumes:
#  postgresql-data:
#    name: postgresql-data
